# Generated by Django 4.1 on 2022-11-22 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_fasegrupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseGruposPaises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fixtures.fasegrupos')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fixtures.paises')),
            ],
        ),
    ]
