# Generated by Django 4.1 on 2022-11-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_fasegrupospaises'),
    ]

    operations = [
        migrations.AddField(
            model_name='paises',
            name='imagen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
